"""
Django settings for feeds project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

project_dirname = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
asset_dirname = 'assets'


def project_path(*args):
    """ Gets a path relative to the project's root directory. """

    return os.path.join(project_dirname, *args)


def asset_path(*args):
    """ Gets a path under the project's assets directory. """

    return os.path.join(project_path(asset_dirname), *args)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w()+un$3%gq4f+b8$)(vp7tfyoqc1@vzf-%x)42465%=#81_@f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_comments_xtd',
    'django_comments',
    'django_extensions',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'feeds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['main/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'feeds.context_processors.providers'
            ],
        },
    },
]

WSGI_APPLICATION = 'feeds.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = asset_path('static')

FEEDS = [
    ('Guardian', 'https://www.theguardian.com/uk/rss'),
    ('Daily Mail', 'https://www.dailymail.co.uk/home/index.rss'),
    ('Independent', 'https://www.independent.co.uk/rss'),
    ('Breitbart', 'https://feeds.feedburner.com/breitbart'),
    ('Reuters', 'https://uk.reuters.com/tools/rss'),
    ('BBC', 'http://feeds.bbci.co.uk/news/rss.xml'),
    ('Anarchist News', 'https://anarchistnews.org/rss.xml'),
    ('Telegraph', 'http://www.telegraph.co.uk/newsfeed/rss/news_main.xml'),
    ('The Sun', 'https://www.thesun.co.uk/feed/'),
    ('Huffington Post', 'https://www.huffingtonpost.co.uk/rss/index.xml'),
    ('New European', 'https://www.theneweuropean.co.uk/cmlink/the-new-european-latest-news-1-4999786'),
]

SITE_ID = '667'

COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 10
COMMENTS_XTD_CONFIRM_MAIL = False
